* fake_d

Fake a two dimensional array using a one dimensional array.

Why? 2d arrays can be a pain to manage in low level languages. This library gives you the interface of a 2d array with the advantages of a 1d array (simpler allocation, easier use of stack memory, et cetera).

6 items are provided:

- ~int FD_upper_bound~
- ~int FD_get_total_length()~
- ~void FD_fill(int arr[], int filler)~
- ~void FD_zero(int arr[])~
- ~void FD_set(int arr[], int x, int y, int val)~
- ~int FD_get(int arr[], int x, int y)~


~FD_upper_bound~ defaults to ~100~, but you can set it to accomodate whatever you need. Declare this before anything else.

Include the lib:

#+BEGIN_SRC C
#include "fake_d.h"
#+END_SRC

If you plan to change the upper bound, declare it:

#+BEGIN_SRC C
FD_upper_bound = 500;
#+END_SRC

Then declare your array:

#+BEGIN_SRC C
int arr[FD_get_total_length()];
#+END_SRC

Optionally, you can zero or fill the array:

#+BEGIN_SRC C
FD_zero(arr);
#+END_SRC

#+BEGIN_SRC C
FD_fill(arr, -1);
#+END_SRC

Now, you can freely, get and set ~x~ and ~y~ coordinates as if you were using a 2d array:

#+BEGIN_SRC C
FD_set(arr, 11, 7, 42);

printf(
    "11, 7 = %i\n",
    FD_get(arr, 11, 7));

// 11, 7 = 42
#+END_SRC

-----

[[https://repl.it/github/ryanpcmcquen/fake_d][Test it on repl.it]]
